apiVersion: apps/v1
metadata:
  name: ${app.name}
spec:
  selector:
    matchLabels:
      app: ${app.name}
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${app.name}
    spec:
      containers:
        - name: ${app.name}
          image: ${image.tag}
          ports:
            - name: http-port
              containerPort: 8080
