apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  namespace: ${project.groupId}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: project
    provider: provider
    group: group
  type: NodePort